Q1

In [2]:
import requests
import pandas as pd

url = "http://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD"
params = {"format": "json", "per_page": 20000}

respones = requests.get(url, params=params)
data = respones.json()

gdp_df = pd.json_normalize(data[1])
gdp_df.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,AFE,2025,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
1,AFE,2024,4106.434140,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
2,AFE,2023,4083.993003,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
3,AFE,2022,4106.501907,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
4,AFE,2021,4056.113017,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern

Q2.

In [5]:
url = "http://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN"
params = {"format": "json", "per_page": 20000}

respones = requests.get(url, params=params)
data = respones.json()

life_exp_df = pd.json_normalize(data[1])
life_exp_df.head()

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,AFE,2025,NaN,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
1,AFE,2024,65.349930,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
2,AFE,2023,65.146228,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
3,AFE,2022,64.487152,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
4,AFE,2021,62.979999,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern

Q3.

In [11]:
gdp_clean = gdp_df[["countryiso3code", "country.value", "date", "value"]].rename(
    columns={"value": "gdp_per_capita_ppp"})
    
Life_clean = life_exp_df[["countryiso3code", "country.value", "date", "value"]].rename(
    columns={"value": "life_expectancy"})

merged_df = pd.merge(  gdp_clean, Life_clean,
    on=["countryiso3code", "country.value", "date"],
    how="outer")

merged_df.head()

  countryiso3code country.value  date  gdp_per_capita_ppp  life_expectancy
0                   High income  1960                 NaN        68.336473
1                   High income  1961                 NaN        68.709260
2                   High income  1962                 NaN        68.663908
3                   High income  1963                 NaN        68.945032
4                   High income  1964                 NaN        69.385162

Q4.

In [23]:
url = "http://api.worldbank.org/v2/country"
params = {"format": "json", "per_page": 400}

respones = requests.get(url, params=params)
data = respones.json()

country_df = pd.json_normalize(data[1])
country_df.head()

,id,iso2Code,name,capitalCity,longitude,latitude,region.id,region.iso2code,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,ABW,AW,Aruba,Oranjestad,-70.0167,12.5167,LCN,ZJ,Latin America & Caribbean,,,,HIC,XD,High income,LNX,XX,Not classified
1,AFE,ZH,Africa Eastern and Southern,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
2,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,MEA,ZQ,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
3,AFR,A9,Africa,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates
4,AFW,ZI,Africa Western and Central,,,,NA,NA,Aggregates,,,,NA,NA,Aggregates,,,Aggregates

In [26]:
country_clean = country_df[["id", "region.value", "capitalCity", "incomeLevel.value"]].rename(
    columns={"id": "countryiso3code"})

full_df = pd.merge(merged_df, country_clean, on="countryiso3code", how="left")

full_df = full_df[full_df["region.value"] != "Aggregates"]

full_df.head()

,countryiso3code,country.value,date,gdp_per_capita_ppp,life_expectancy,region.value,capitalCity,incomeLevel.value
0,,High income,1960,NaN,68.336473,NaN,NaN,NaN
1,,High income,1961,NaN,68.709260,NaN,NaN,NaN
2,,High income,1962,NaN,68.663908,NaN,NaN,NaN
3,,High income,1963,NaN,68.945032,NaN,NaN,NaN
4,,High income,1964,NaN,69.385162,NaN,NaN,NaN